/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./../src/components/animation.vue')['default']
    BreadCrumbs: typeof import('./../src/components/BreadCrumbs.vue')['default']
    Captcha: typeof import('./../src/components/Captcha.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    LkButton: typeof import('./../src/components/From/lk-button.vue')['default']
    LkInput: typeof import('./../src/components/From/lk-input.vue')['default']
    Markdown: typeof import('./../src/components/editor/markdown.vue')['default']
    Notification: typeof import('./../src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./../src/components/topBar.vue')['default']
    WangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
  }
}
